Add "run-all-if-changed" parameter, so allow re-triggering all tests if jest.config.js or package.json changes
Khan/jest-action pull request #17
Opened 2021-07-27 17:41 UTC by jaredly

## Summary:
This allows us to specify in the repo which files would trigger a full recheck.

Jira: https://khanacademy.atlassian.net/browse/FEI-3520

## Test plan:
🤞 try using it in webapp

2021-07-28 18:02 UTC, jeresig approved these changes
Awesome, thank you!

2021-07-30 21:15 UTC, lillialexis requested changes

2021-07-30 21:15 UTC, lillialexis commented on jest.js
> +    const current = process.cwd();
I thought I reviewed this... don't we want to get the path from the `workingDirectory` arg above? I think it breaks in some cases otherwise....

2021-08-02 17:39 UTC, lillialexis approved these changes

2021-08-03 18:38 UTC, merged